### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by blackshot** [mr-azazael/LightweightCharts.Blazor#2]
i could not find any documentation of the wrapper, is it planned?

**Comment by mr-azazael** [comment]
Most of the trading view library is mapped 1:1 (the exceptions are described under the Limitations, in the Readme file) and
all public members have summaries with links that point to the mapped item from the trading view library.
You can use their documentation for your purposes as the member naming (and api structure) is more or less the same.
As for the library version, the nugget version reflects the used library version (3.8.0 at the time of writing).
