### ISSUE TITLE
LayoutOptions Background property change has no effect

### ISSUE THREAD

**Issue by cyberyaga** [mr-azazael/LightweightCharts.Blazor#3]
Hello... Thanks for the hard work with this wrapper. It's pretty good.

I am trying to change the background color on the chart.

Other properties like TextColor or FontSize work just fine. But not Background.

Here is my code to initialize the component:
`    
async void InitializeChartComponent(ChartComponent chart)
    {
        await chart.InitializationCompleted;
        chart.Clicked += OnChartClicked!;
        chart.CrosshairMoved += OnChartCrosshairMoved!;

        await chart.ApplyOptions(new LightweightCharts.Blazor.Customization.Chart.ChartOptions
			{
				LeftPriceScale = new LightweightCharts.Blazor.Customization.Chart.PriceScaleOptions
				{
					Visible = false
				},
				RightPriceScale = new LightweightCharts.Blazor.Customization.Chart.PriceScaleOptions
				{
					ScaleMargins = new LightweightCharts.Blazor.Customization.PriceScaleMargins
					{
						Bottom = 0.1d,
						Top = 0
					}
				},
				OverlayPriceScale = new LightweightCharts.Blazor.Customization.Chart.BasePriceScaleOptions
				{
					ScaleMargins = new LightweightCharts.Blazor.Customization.PriceScaleMargins
					{
						Bottom = 0,
						Top = 0.9d
					}
				},
				Layout = new LightweightCharts.Blazor.Customization.Chart.LayoutOptions
				{
					Background = new LightweightCharts.Blazor.Customization.Chart.SolidColor { Color = Color.RoyalBlue },
					TextColor = Color.Red,
					FontSize = 14
				}
			});

		await SetupCandlestickSeries(chart);
		await SetupHistogramSeries(chart);

		var timeScale = await chart.TimeScaleAsync();
		await timeScale.FitContent();
		initialLoad = false;
	}
`

This compiles just fine, but the background property is the only one that has no effect when rendered. The TextColor and FontSize do change.

Thanks in advance for the help.

**Comment by mr-azazael** [comment]
The issue seems to be that the default json converter is converting only the values defined on the Background property type, which is 'BackgroundColor', an abstract type, ignoring any extra property (like Color on SolidColor or TopColor/BottomColor VerticalGradientColor).

I'll address this in the next update.

**Comment by mr-azazael** [comment]
I've upgraded the project to .net8 and fixed the serialization for the abstract properties, background in this case. 
In the main branch, the background options are serialized properly now (examples included).

I'll close this issue when the new package version is released.

**Comment by mr-azazael** [comment]
Released in nuget version 4.1.2.1.
