### ISSUE TITLE
OI Charts

### ISSUE THREAD

**Issue by kiranmaya** [mr-azazael/LightweightCharts.Blazor#5]
hi,
want to oi chart like the below screenshot, histogram series works on the bottom panel, need to shift to price panel,will the existing histogram series work for it,or need to do a custom series? does this wrapper support custom series? 
Give me your idea or a way to achieve to this. 
![Screenshot_2](https://github.com/mr-azazael/LightweightCharts.Blazor/assets/3712631/312dd02d-bca5-4f91-9651-2cfd6ae0da77)
need to bring option data into charts .
![Screenshot_3](https://github.com/mr-azazael/LightweightCharts.Blazor/assets/3712631/490f2f39-4780-4050-b256-9ab54f86f5cb)

Thanks 
kiran

**Comment by mr-azazael** [comment]
Hello,

No there are no series in the library that go on the price axis.
For more info and demos, see the official library page: https://www.tradingview.com/lightweight-charts/
